trigger: none

pool:
 vmImage: windows-latest

stages:
  - stage: CheckoutCode
    jobs:
      - job: 'CheckoutGitCode'
        steps:
          - checkout: self
  - stage: 'Build'
    jobs: 
     - job: 'BuildJob'
       steps:
         - task: Maven@4
           inputs: 
            mavenPomFile: "pom.xml"
            goals: 'install'
            publishJUnitResults: false
            javaHomeOption: JDKVersion
            mavenVersionOption: Default
            mavenAuthenticateFeed: false
            effectivePomSkip: true
            sonarQubeRunAnalysis: false

  - stage: 'PublishArtifact_stage' 
    jobs:
     - job: 'Publish_artifactjob'
       steps:
        - task: PublishPipelineArtifact@1
          inputs: 
           targetPath: '$(Pipeline.Workspace)'
           artifact: 'DemoArtifactYaml'
           publishLocation: pipeline
           
  - stage: 'Downloadartifact'
    jobs:
      - deployment: Deploy
        environment: Stage
        strategy: 
         runOnce:
           deploy:
             steps:
               - task: DownloadPipelineArtifact@2
                 inputs:
                    buildType: 'specific'
                    project: '9719fd0e-0c0e-4769-aa5a-bd8aa892b740'
                    definition: '7'
                    specificBuildWithTriggering: true
                    buildVersionToDownload: 'latest'
                    artifactName: 'DemoArtifactYAML'
                    targetPath: '$(Pipeline.Workspace)'
